<?php
/**
 * CollectionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * OpenAPI spec version: 12.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CollectionsTest Class Doc Comment
 *
 * @category    Class
 * @description Collections
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CollectionsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Collections"
     */
    public function testCollections()
    {
    }

    /**
     * Test attribute "collection"
     */
    public function testPropertyCollection()
    {
    }

    /**
     * Test attribute "icon"
     */
    public function testPropertyIcon()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "display_template"
     */
    public function testPropertyDisplayTemplate()
    {
    }

    /**
     * Test attribute "hidden"
     */
    public function testPropertyHidden()
    {
    }

    /**
     * Test attribute "singleton"
     */
    public function testPropertySingleton()
    {
    }

    /**
     * Test attribute "translations"
     */
    public function testPropertyTranslations()
    {
    }

    /**
     * Test attribute "archive_field"
     */
    public function testPropertyArchiveField()
    {
    }

    /**
     * Test attribute "archive_app_filter"
     */
    public function testPropertyArchiveAppFilter()
    {
    }

    /**
     * Test attribute "archive_value"
     */
    public function testPropertyArchiveValue()
    {
    }

    /**
     * Test attribute "unarchive_value"
     */
    public function testPropertyUnarchiveValue()
    {
    }

    /**
     * Test attribute "sort_field"
     */
    public function testPropertySortField()
    {
    }

    /**
     * Test attribute "accountability"
     */
    public function testPropertyAccountability()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "item_duplication_fields"
     */
    public function testPropertyItemDuplicationFields()
    {
    }

    /**
     * Test attribute "sort"
     */
    public function testPropertySort()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "collapse"
     */
    public function testPropertyCollapse()
    {
    }

    /**
     * Test attribute "preview_url"
     */
    public function testPropertyPreviewUrl()
    {
    }

    /**
     * Test attribute "collection_divider"
     */
    public function testPropertyCollectionDivider()
    {
    }

    /**
     * Test attribute "preview_divider"
     */
    public function testPropertyPreviewDivider()
    {
    }

    /**
     * Test attribute "archive_divider"
     */
    public function testPropertyArchiveDivider()
    {
    }

    /**
     * Test attribute "sort_divider"
     */
    public function testPropertySortDivider()
    {
    }

    /**
     * Test attribute "accountability_divider"
     */
    public function testPropertyAccountabilityDivider()
    {
    }

    /**
     * Test attribute "duplication_divider"
     */
    public function testPropertyDuplicationDivider()
    {
    }
}
