<?php
/**
 * PermissionsBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * OpenAPI spec version: 12.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PermissionsBodyTest Class Doc Comment
 *
 * @category    Class
 * @description PermissionsBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PermissionsBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PermissionsBody"
     */
    public function testPermissionsBody()
    {
    }

    /**
     * Test attribute "collection"
     */
    public function testPropertyCollection()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "create"
     */
    public function testPropertyCreate()
    {
    }

    /**
     * Test attribute "delete"
     */
    public function testPropertyDelete()
    {
    }

    /**
     * Test attribute "explain"
     */
    public function testPropertyExplain()
    {
    }

    /**
     * Test attribute "read"
     */
    public function testPropertyRead()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "read_field_blacklist"
     */
    public function testPropertyReadFieldBlacklist()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "status_blacklist"
     */
    public function testPropertyStatusBlacklist()
    {
    }

    /**
     * Test attribute "update"
     */
    public function testPropertyUpdate()
    {
    }

    /**
     * Test attribute "write_field_blacklist"
     */
    public function testPropertyWriteFieldBlacklist()
    {
    }
}
