<?php
/**
 * ItemsSubsidiaryAccountApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * OpenAPI spec version: 12.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemsSubsidiaryAccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsSubsidiaryAccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createItemsSubsidiaryAccount
     *
     * Create an Item.
     *
     */
    public function testCreateItemsSubsidiaryAccount()
    {
    }

    /**
     * Test case for deleteSingleItemsSubsidiaryAccount
     *
     * Delete an Item.
     *
     */
    public function testDeleteSingleItemsSubsidiaryAccount()
    {
    }

    /**
     * Test case for readItemsSubsidiaryAccount
     *
     * List Items.
     *
     */
    public function testReadItemsSubsidiaryAccount()
    {
    }

    /**
     * Test case for readSingleItemsSubsidiaryAccount
     *
     * Retrieve an Item.
     *
     */
    public function testReadSingleItemsSubsidiaryAccount()
    {
    }

    /**
     * Test case for updateSingleItemsSubsidiaryAccount
     *
     * Update an Item.
     *
     */
    public function testUpdateSingleItemsSubsidiaryAccount()
    {
    }
}
