<?php
/**
 * ItemsCityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Dynamic API Specification
 *
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * OpenAPI spec version: 12.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.43
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemsCityApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ItemsCityApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createItemsCity
     *
     * Create an Item.
     *
     */
    public function testCreateItemsCity()
    {
    }

    /**
     * Test case for deleteSingleItemsCity
     *
     * Delete an Item.
     *
     */
    public function testDeleteSingleItemsCity()
    {
    }

    /**
     * Test case for readItemsCity
     *
     * List Items.
     *
     */
    public function testReadItemsCity()
    {
    }

    /**
     * Test case for readSingleItemsCity
     *
     * Retrieve an Item.
     *
     */
    public function testReadSingleItemsCity()
    {
    }

    /**
     * Test case for updateSingleItemsCity
     *
     * Update an Item.
     *
     */
    public function testUpdateSingleItemsCity()
    {
    }
}
